<?php
/**
 * Tests UTM key usage in Fixes setting field renderers.
 *
 * @package Accessibility_Checker
 */

use PHPUnit\Framework\TestCase;
use EqualizeDigital\AccessibilityChecker\Admin\AdminPage\FixesSettingType\Checkbox;
use EqualizeDigital\AccessibilityChecker\Admin\AdminPage\FixesSettingType\Text;

/**
 * Stub class exposing the Text trait renderer.
 */
class FixesSettingTypeUtmTextStub {
	use Text;
}

/**
 * Stub class exposing the Checkbox trait renderer.
 */
class FixesSettingTypeUtmCheckboxStub {
	use Checkbox;
}

/**
 * Tests for UTM campaign/content query key correctness.
 */
class FixesSettingTypeUtmTest extends TestCase {

	/**
	 * Help link generated by text field should use underscore UTM keys.
	 */
	public function test_text_help_link_uses_underscore_utm_keys() {
		ob_start();
		FixesSettingTypeUtmTextStub::text(
			[
				'name'        => 'edac_fix_test_field',
				'description' => 'Test description',
				'label'       => 'Test Label',
				'help_id'     => 1234,
			]
		);
		$output = ob_get_clean();

		$this->assertStringContainsString( 'utm_campaign=fix-description', $output );
		$this->assertStringContainsString( 'utm_content=edac_fix_test_field', $output );
		$this->assertStringNotContainsString( 'utm-campaign=fix-description', $output );
		$this->assertStringNotContainsString( 'utm-content=edac_fix_test_field', $output );
	}

	/**
	 * Help link generated by checkbox field should use underscore UTM keys.
	 */
	public function test_checkbox_help_link_uses_underscore_utm_keys() {
		ob_start();
		FixesSettingTypeUtmCheckboxStub::checkbox(
			[
				'name'        => 'edac_fix_test_checkbox',
				'description' => 'Test description',
				'label'       => 'Test Checkbox Label',
				'help_id'     => 5678,
			]
		);
		$output = ob_get_clean();

		$this->assertStringContainsString( 'utm_campaign=fix-description', $output );
		$this->assertStringContainsString( 'utm_content=edac_fix_test_checkbox', $output );
		$this->assertStringNotContainsString( 'utm-campaign=fix-description', $output );
		$this->assertStringNotContainsString( 'utm-content=edac_fix_test_checkbox', $output );
	}
}
