
<?php
/**
 * Returns an array of WCAG Success Criteria and relevant information.
 *
 * @package Accessibility_Checker
 */

return [
    [
        'number'   => '1.1.1',
        'title'    => esc_html__( 'Non-text Content', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.1 Text Alternatives', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with dexterity impairments using voice control', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#non-text-content',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#non-text-content',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.1',
        'title'    => esc_html__( 'Prerecorded Audio-only and Video-only', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#audio-only-and-video-only-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/audio-only-and-video-only-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#audio-only-and-video-only-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.2',
        'title'    => esc_html__( 'Captions (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#captions-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/captions-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#captions-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.3',
        'title'    => esc_html__( 'Audio Description or Media Alternative (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#audio-description-or-media-alternative-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/audio-description-or-media-alternative-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#audio-description-or-media-alternative-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.4',
        'title'    => esc_html__( 'Captions (Live)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#captions-live',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/captions-live.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#captions-live',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.5',
        'title'    => esc_html__( 'Audio Description (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#audio-description-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/audio-description-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#audio-description-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.6',
        'title'    => esc_html__( 'Sign Language (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#sign-language-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/sign-language-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#sign-language-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.7',
        'title'    => esc_html__( 'Extended Audio Description (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#extended-audio-description-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/extended-audio-description-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#extended-audio-description-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.8',
        'title'    => esc_html__( 'Media Alternative (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'Deaf-blind people', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#media-alternative-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/media-alternative-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#media-alternative-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.9',
        'title'    => esc_html__( 'Audio-only (Live)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#audio-only-live',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/audio-only-live.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#audio-only-live',
        'tags'     => [],
    ],
    [
        'number'   => '1.3.1',
        'title'    => esc_html__( 'Info and Relationships', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.3 Adaptable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
            esc_html__( 'People with cognitive differences who view interfaces using an adapted layout', 'accessibility-checker' ),
            esc_html__( 'People with dexterity impairments using voice control', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#info-and-relationships',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#info-and-relationships',
        'tags'     => [],
    ],
    [
        'number'   => '1.3.2',
        'title'    => esc_html__( 'Meaningful Sequence', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.3 Adaptable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
            esc_html__( 'People with cognitive differences who view interfaces using an adapted layout', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#meaningful-sequence',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#meaningful-sequence',
        'tags'     => [],
    ],
    [
        'number'   => '1.3.3',
        'title'    => esc_html__( 'Sensory Characteristics', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.3 Adaptable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#sensory-characteristics',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/sensory-characteristics.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#sensory-characteristics',
        'tags'     => [],
    ],
    [
        'number'   => '1.3.4',
        'title'    => esc_html__( 'Orientation', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.1',
        'guidelines' => esc_html__( '1.3 Adaptable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#orientation',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/orientation.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#orientation',
        'tags'     => [],
    ],
    [
        'number'   => '1.3.5',
        'title'    => esc_html__( 'Identify Input Purpose', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.1',
        'guidelines' => esc_html__( '1.3 Adaptable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with cognitive disabilities or limited short-term memory or reading disabilities', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#identify-input-purpose',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#identify-input-purpose',
        'tags'     => [],
    ],
    [
        'number'   => '1.3.6',
        'title'    => esc_html__( 'Identify Purpose', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.1',
        'guidelines' => esc_html__( '1.3 Adaptable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with cognitive disabilities or limited short-term memory or reading disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#identify-purpose',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/identify-purpose.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#identify-purpose',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.1',
        'title'    => esc_html__( 'Use of Color', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
            esc_html__( 'Color blind people', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#use-of-color',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#use-of-color',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.10',
        'title'    => esc_html__( 'Reflow', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.1',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People on mobile devices', 'accessibility-checker' ),
            esc_html__( 'People with low vision', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#reflow',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/reflow.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#reflow',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.11',
        'title'    => esc_html__( 'Non-text Contrast', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.1',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with low vision', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#non-text-contrast',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#non-text-contrast',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.12',
        'title'    => esc_html__( 'Text Spacing', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.1',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
            esc_html__( 'People with low vision', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#text-spacing',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#text-spacing',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.13',
        'title'    => esc_html__( 'Content on Hover or Focus', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.1',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities', 'accessibility-checker' ),
            esc_html__( 'People with dexterity impairments', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#content-on-hover-or-focus',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.2',
        'title'    => esc_html__( 'Audio Control', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'People with ADD or difficulty focusing on content without distraction', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#audio-control',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/audio-control.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#audio-control',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.3',
        'title'    => esc_html__( 'Contrast (Minimum)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People on mobile devices in a sunny environment', 'accessibility-checker' ),
            esc_html__( 'People with low vision', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#contrast-minimum',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#contrast-minimum',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.4',
        'title'    => esc_html__( 'Resize text', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with low vision', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#resize-text',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#resize-text',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.5',
        'title'    => esc_html__( 'Images of Text', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#images-of-text',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#images-of-text',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.6',
        'title'    => esc_html__( 'Contrast (Enhanced)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People on mobile devices in a sunny environment', 'accessibility-checker' ),
            esc_html__( 'People with low vision', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#contrast-enhanced',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#contrast-enhanced',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.7',
        'title'    => esc_html__( 'Low or No Background Audio', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#low-or-no-background-audio',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/low-or-no-background-audio.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#low-or-no-background-audio',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.8',
        'title'    => esc_html__( 'Visual Presentation', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
            esc_html__( 'People with low vision', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#visual-presentation',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/visual-presentation.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#visual-presentation',
        'tags'     => [],
    ],
    [
        'number'   => '1.4.9',
        'title'    => esc_html__( 'Images of Text (No Exception)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.4 Distinguishable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#images-of-text-no-exception',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/images-of-text-no-exception.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#images-of-text-no-exception',
        'tags'     => [],
    ],
    [
        'number'   => '2.1.1',
        'title'    => esc_html__( 'Keyboard', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.1 Keyboard Accessible', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#keyboard',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/keyboard.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#keyboard',
        'tags'     => [],
    ],
    [
        'number'   => '2.1.2',
        'title'    => esc_html__( 'No Keyboard Trap', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.1 Keyboard Accessible', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#no-keyboard-trap',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/no-keyboard-trap.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#no-keyboard-trap',
        'tags'     => [],
    ],
    [
        'number'   => '2.1.3',
        'title'    => esc_html__( 'Keyboard (No Exception)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.1 Keyboard Accessible', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#keyboard-no-exception',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/keyboard-no-exception.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#keyboard-no-exception',
        'tags'     => [],
    ],
    [
        'number'   => '2.1.4',
        'title'    => esc_html__( 'Character Key Shortcuts', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.1',
        'guidelines' => esc_html__( '2.1 Keyboard Accessible', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#character-key-shortcuts',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#character-key-shortcuts',
        'tags'     => [],
    ],
    [
        'number'   => '2.2.1',
        'title'    => esc_html__( 'Timing Adjustable', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.2 Enough Time', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who need more time to react', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#timing-adjustable',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#timing-adjustable',
        'tags'     => [],
    ],
    [
        'number'   => '2.2.2',
        'title'    => esc_html__( 'Pause, Stop, Hide', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.2 Enough Time', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with ADD or difficulty focusing on content without distraction', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#pause-stop-hide',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#pause-stop-hide',
        'tags'     => [],
    ],
    [
        'number'   => '2.2.3',
        'title'    => esc_html__( 'No Timing', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.2 Enough Time', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who need more time to react', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#no-timing',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/no-timing.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#no-timing',
        'tags'     => [],
    ],
    [
        'number'   => '2.2.4',
        'title'    => esc_html__( 'Interruptions', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.2 Enough Time', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who need more time to react', 'accessibility-checker' ),
            esc_html__( 'People with ADD or difficulty focusing on content without distraction', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#interruptions',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/interruptions.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#interruptions',
        'tags'     => [],
    ],
    [
        'number'   => '2.2.5',
        'title'    => esc_html__( 'Re-authenticating', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.2 Enough Time', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who need more time to react', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#re-authenticating',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/re-authenticating.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#re-authenticating',
        'tags'     => [],
    ],
    [
        'number'   => '2.2.6',
        'title'    => esc_html__( 'Timeouts', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.1',
        'guidelines' => esc_html__( '2.2 Enough Time', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who need more time to react', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#timeouts',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/timeouts.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#timeouts',
        'tags'     => [],
    ],
    [
        'number'   => '2.3.1',
        'title'    => esc_html__( 'Three Flashes or Below Threshold', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.3 Seizures and Physical Reactions', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with photosensitive epilepsy and other photosensitive seizure disorders', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#three-flashes-or-below-threshold',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#three-flashes-or-below-threshold',
        'tags'     => [],
    ],
    [
        'number'   => '2.3.2',
        'title'    => esc_html__( 'Three Flashes', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.3 Seizures and Physical Reactions', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with photosensitive epilepsy and other photosensitive seizure disorders', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#three-flashes',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/three-flashes.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#three-flashes',
        'tags'     => [],
    ],
    [
        'number'   => '2.3.3',
        'title'    => esc_html__( 'Animation from Interactions', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.1',
        'guidelines' => esc_html__( '2.3 Seizures and Physical Reactions', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with vestibular (inner ear) disorders where movement can cause dizziness/headaches and nausea', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#animation-from-interactions',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#animation-from-interactions',
        'tags'     => [],
    ],
    [
        'number'   => '2.4.1',
        'title'    => esc_html__( 'Bypass Blocks', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#bypass-blocks',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#bypass-blocks',
        'tags'     => [],
    ],
    [
        'number'   => '2.4.10',
        'title'    => esc_html__( 'Section Headings', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities or limited short-term memory or reading disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#section-headings',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/section-headings.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#section-headings',
        'tags'     => [],
    ],
    [
        'number'   => '2.4.11',
        'title'    => esc_html__( 'Focus Not Obscured (Minimum)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.2',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG22/quickref/#focus-not-obscured-minimum',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG22/#focus-not-obscured-minimum',
        'tags'     => [],
    ],
    [
        'number'   => '',
        'title'    => esc_html__( '2.4.12 Focus Not Obscured (Enhanced)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.2',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG22/quickref/#focus-not-obscured-enhanced',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-enhanced.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG22/#focus-not-obscured-enhanced',
        'tags'     => [],
    ],
    [
        'number'   => '2.4.13',
        'title'    => esc_html__( 'Focus Appearance', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.2',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG22/quickref/#focus-appearance',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG22/#focus-appearance',
        'tags'     => [],
    ],
    [
        'number'   => '2.4.2',
        'title'    => esc_html__( 'Page Titled', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with cognitive disabilities or limited short-term memory or reading disabilities', 'accessibility-checker' ),
            esc_html__( 'People with severe mobility impairments relying on audio to navigate the web', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#page-titled',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#page-titled',
        'tags'     => [],
    ],
    [
        'number'   => '2.4.3',
        'title'    => esc_html__( 'Focus Order', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'People with low vision', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#focus-order',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#focus-order',
        'tags'     => [],
    ],
    [
        'number'   => '2.4.4',
        'title'    => esc_html__( 'Link Purpose (In Context)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#link-purpose-in-context',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#link-purpose-in-context',
        'tags'     => [],
    ],
    [
        'number'   => '2.4.5',
        'title'    => esc_html__( 'Multiple Ways', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#multiple-ways',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/multiple-ways.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#multiple-ways',
        'tags'     => [],
    ],
    [
        'number'   => '2.4.6',
        'title'    => esc_html__( 'Headings and Labels', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities or limited short-term memory or reading disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#headings-and-labels',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/headings-and-labels.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#headings-and-labels',
        'tags'     => [],
    ],
    [
        'number'   => '2.4.7',
        'title'    => esc_html__( 'Focus Visible', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'People with low vision', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#focus-visible',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#focus-visible',
        'tags'     => [],
    ],
    [
        'number'   => '2.4.8',
        'title'    => esc_html__( 'Location', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities or limited short-term memory or reading disabilities', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#location',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/location.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#location',
        'tags'     => [],
    ],
    [
        'number'   => '2.4.9',
        'title'    => esc_html__( 'Link Purpose (Link Only)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '2.4 Navigable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#link-purpose-link-only',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-link-only.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#link-purpose-link-only',
        'tags'     => [],
    ],
    [
        'number'   => '2.5.1',
        'title'    => esc_html__( 'Pointer Gestures', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.1',
        'guidelines' => esc_html__( '2.5 Input Modalities', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#pointer-gestures',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#pointer-gestures',
        'tags'     => [],
    ],
    [
        'number'   => '2.5.2',
        'title'    => esc_html__( 'Pointer Cancellation', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.1',
        'guidelines' => esc_html__( '2.5 Input Modalities', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#pointer-cancellation',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/pointer-cancellation.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#pointer-cancellation',
        'tags'     => [],
    ],
    [
        'number'   => '2.5.3',
        'title'    => esc_html__( 'Label in Name', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.1',
        'guidelines' => esc_html__( '2.5 Input Modalities', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with dexterity impairments using voice control', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#label-in-name',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#label-in-name',
        'tags'     => [],
    ],
    [
        'number'   => '2.5.4',
        'title'    => esc_html__( 'Motion Actuation', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.1',
        'guidelines' => esc_html__( '2.5 Input Modalities', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#motion-actuation',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/motion-actuation.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#motion-actuation',
        'tags'     => [],
    ],
    [
        'number'   => '2.5.5',
        'title'    => esc_html__( 'Target Size', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.1',
        'guidelines' => esc_html__( '2.5 Input Modalities', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People using a mobile device in environments where they are exposed to shaking (such as public transportation)', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments including hand tremors', 'accessibility-checker' ),
            esc_html__( 'People with low vision', 'accessibility-checker' ),
            esc_html__( 'People with with large fingers or who are operating the device with only a part of their finger or knuckle', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#target-size',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/target-size.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#target-size',
        'tags'     => [],
    ],
    [
        'number'   => '2.5.6',
        'title'    => esc_html__( 'Concurrent Input Mechanisms', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.1',
        'guidelines' => esc_html__( '2.5 Input Modalities', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#concurrent-input-mechanisms',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/concurrent-input-mechanisms.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#concurrent-input-mechanisms',
        'tags'     => [],
    ],
    [
        'number'   => '2.5.7',
        'title'    => esc_html__( 'Dragging Movements', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.2',
        'guidelines' => esc_html__( '2.5 Input Modalities', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG22/quickref/#dragging-movements',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG22/#dragging-movements',
        'tags'     => [],
    ],
    [
        'number'   => '2.5.8',
        'title'    => esc_html__( 'Target Size (Minimum)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.2',
        'guidelines' => esc_html__( '2.5 Input Modalities', 'accessibility-checker' ),
        'principles' => esc_html__( 'Operable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People on mobile devices', 'accessibility-checker' ),
            esc_html__( 'People with dexterity impairments', 'accessibility-checker' ),
            esc_html__( 'People with low vision', 'accessibility-checker' ),
            esc_html__( 'People with with large fingers or who are operating the device with only a part of their finger or knuckle', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG22/quickref/#target-size-minimum',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG22/#target-size-minimum',
        'tags'     => [],
    ],
    [
        'number'   => '3.1.1',
        'title'    => esc_html__( 'Language of Page', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.1 Readable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Language learners', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#language-of-page',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/language-of-page.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#language-of-page',
        'tags'     => [],
    ],
    [
        'number'   => '3.1.2',
        'title'    => esc_html__( 'Language of Parts', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.1 Readable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Language learners', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#language-of-parts',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#language-of-parts',
        'tags'     => [],
    ],
    [
        'number'   => '3.1.3',
        'title'    => esc_html__( 'Unusual Words', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.1 Readable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#unusual-words',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/unusual-words.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#unusual-words',
        'tags'     => [],
    ],
    [
        'number'   => '3.1.4',
        'title'    => esc_html__( 'Abbreviations', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.1 Readable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#abbreviations',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/abbreviations.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#abbreviations',
        'tags'     => [],
    ],
    [
        'number'   => '3.1.5',
        'title'    => esc_html__( 'Reading Level', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.1 Readable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#reading-level',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/reading-level.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#reading-level',
        'tags'     => [],
    ],
    [
        'number'   => '3.1.6',
        'title'    => esc_html__( 'Pronunciation', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.1 Readable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#pronunciation',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/pronunciation.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#pronunciation',
        'tags'     => [],
    ],
    [
        'number'   => '3.2.1',
        'title'    => esc_html__( 'On Focus', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.2 Predictable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#on-focus',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/on-focus.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#on-input',
        'tags'     => [],
    ],
    [
        'number'   => '3.2.2',
        'title'    => esc_html__( 'On Input', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.2 Predictable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#on-input',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/on-input.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#on-input',
        'tags'     => [],
    ],
    [
        'number'   => '3.2.3',
        'title'    => esc_html__( 'Consistent Navigation', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.2 Predictable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#consistent-navigation',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/consistent-navigation.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#consistent-navigation',
        'tags'     => [],
    ],
    [
        'number'   => '3.2.4',
        'title'    => esc_html__( 'Consistent Identification', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.2 Predictable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#consistent-identification',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#consistent-identification',
        'tags'     => [],
    ],
    [
        'number'   => '3.2.5',
        'title'    => esc_html__( 'Change on Request', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.2 Predictable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People who rely on keyboard control', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
            esc_html__( 'People with dexterity and mobility impairments', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#change-on-request',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/change-on-request.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#change-on-request',
        'tags'     => [],
    ],
    [
        'number'   => '3.2.6',
        'title'    => esc_html__( 'Consistent Help', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.2',
        'guidelines' => esc_html__( '3.2 Predictable', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG22/quickref/#consistent-help',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG22/Understanding/consistent-help.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG22/#consistent-help',
        'tags'     => [],
    ],
    [
        'number'   => '3.3.1',
        'title'    => esc_html__( 'Error Identification', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.3 Input Assistance', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#error-identification',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/error-identification.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#error-identification',
        'tags'     => [],
    ],
    [
        'number'   => '3.3.2',
        'title'    => esc_html__( 'Labels or Instructions', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.3 Input Assistance', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#labels-or-instructions',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#labels-or-instructions',
        'tags'     => [],
    ],
    [
        'number'   => '3.3.3',
        'title'    => esc_html__( 'Error Suggestion', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.3 Input Assistance', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#error-suggestion',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/error-suggestion.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#error-suggestion',
        'tags'     => [],
    ],
    [
        'number'   => '3.3.4',
        'title'    => esc_html__( 'Error Prevention (Legal, Financial, Data)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.3 Input Assistance', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#error-prevention-legal-financial-data',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/error-prevention-legal-financial-data.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#minimize-error-reversible',
        'tags'     => [],
    ],
    [
        'number'   => '3.3.5',
        'title'    => esc_html__( 'Help', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.3 Input Assistance', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#help',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/help.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#help',
        'tags'     => [],
    ],
    [
        'number'   => '3.3.6',
        'title'    => esc_html__( 'Error Prevention (All)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '3.3 Input Assistance', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with cognitive disabilities and reading disabilities', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#error-prevention-all',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/error-prevention-all.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#error-prevention-all',
        'tags'     => [],
    ],
    [
        'number'   => '3.3.7',
        'title'    => esc_html__( 'Redundant Entry', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.2',
        'guidelines' => esc_html__( '3.3 Input Assistance', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'All people including those who do not identify as disabled', 'accessibility-checker' ),
            esc_html__( 'People with severe mobility impairments relying on audio to navigate the web', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG22/quickref/#redundant-entry',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG22/#redundant-entry',
        'tags'     => [],
    ],
    [
        'number'   => 'v',
        'title'    => esc_html__( 'Accessible Authentication (Minimum)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.2',
        'guidelines' => esc_html__( '3.3 Input Assistance', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with cognitive disabilities or limited short-term memory or reading disabilities', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG22/quickref/#accessible-authentication-minimum',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG22/#accessible-authentication-minimum',
        'tags'     => [],
    ],
    [
        'number'   => '3.3.9',
        'title'    => esc_html__( 'Accessible Authentication (Enhanced)', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AAA',
        'version'  => '2.2',
        'guidelines' => esc_html__( '3.3 Input Assistance', 'accessibility-checker' ),
        'principles' => esc_html__( 'Understandable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with cognitive disabilities or limited short-term memory or reading disabilities', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG22/quickref/#accessible-authentication-enhanced',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-enhanced.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG22/#accessible-authentication-enhanced',
        'tags'     => [],
    ],
    [
        'number'   => '4.1.1',
        'title'    => esc_html__( 'Parsing', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '4.1 Compatible', 'accessibility-checker' ),
        'principles' => esc_html__( 'Robust', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with dexterity impairments using voice control', 'accessibility-checker' ),
            esc_html__( 'People with low vision using screen magnifiers', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#parsing',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/parsing.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#parsing',
        'tags'     => [],
    ],
    [
        'number'   => '4.1.2',
        'title'    => esc_html__( 'Name, Role, Value', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '4.1 Compatible', 'accessibility-checker' ),
        'principles' => esc_html__( 'Robust', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with dexterity impairments using voice control', 'accessibility-checker' ),
            esc_html__( 'People with low vision using screen magnifiers', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#name-role-value',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#name-role-value',
        'tags'     => [],
    ],
    [
        'number'   => '4.1.3',
        'title'    => esc_html__( 'Status Messages', 'accessibility-checker' ),
        'criteria_description' => esc_html__('', 'accessibility-checker'),
        'level'    => 'AA',
        'version'  => '2.1',
        'guidelines' => esc_html__( '4.1 Compatible', 'accessibility-checker' ),
        'principles' => esc_html__( 'Robust', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#status-messages',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#status-messages',
        'tags'     => [],
    ],
    [
        'number'   => '0.1',
        'title'    => esc_html__( 'Best Practice', 'accessibility-checker' ),
        'criteria_description' => esc_html__('A usability improvement or convention that enhances accessibility but is not required for WCAG compliance.', 'accessibility-checker'),
        'level'    => '',
        'version'  => '',
        'guidelines' => '',
        'principles' => '',
        'impacted_populations' => [],
        'how_to_meet_url' => '',
        'understanding_url' => '',
        'wcag_url' => '',
        'tags'     => [],
    ],
    [
        'number'   => '0.2',
        'title'    => esc_html__( 'Non-WCAG Accessibility Issue', 'accessibility-checker' ),
        'criteria_description' => esc_html__('A problem that affects users with disabilities but doesn’t map directly to a current WCAG success criterion.', 'accessibility-checker'),
        'level'    => '',
        'version'  => '',
        'guidelines' => '',
        'principles' => '',
        'impacted_populations' => [],
        'how_to_meet_url' => '',
        'understanding_url' => '',
        'wcag_url' => '',
        'tags'     => [],
    ],
];
