<?php
/**
 * Returns an array of WCAG success criteria and relevant information.
 *
 * @package Accessibility_Checker
 */

return [
    [
        'number'   => '1.1.1',
        'title'    => esc_html__( 'Non-text Content', 'accessibility-checker' ),
        'criteria_description' => esc_html__( 'All non-text content that is presented to the user has a text alternative that serves the equivalent purpose.', 'accessibility-checker' ),
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.1 Text Alternatives', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'People with dexterity impairments using voice control', 'accessibility-checker' ),
            esc_html__( 'Screen reader users (blind/low vision and neurodivergent people)', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#non-text-content',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#non-text-content',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.1',
        'title'    => esc_html__( 'Audio-only and Video-only (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => '',
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#audio-only-and-video-only-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/audio-only-and-video-only-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#audio-only-and-video-only-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.2',
        'title'    => esc_html__( 'Captions (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => '',
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#captions-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/captions-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#captions-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.3',
        'title'    => esc_html__( 'Audio Description or Media Alternative (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => '',
        'level'    => 'A',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#audio-description-or-media-alternative-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/audio-description-or-media-alternative-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#audio-description-or-media-alternative-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.4',
        'title'    => esc_html__( 'Captions (Live)', 'accessibility-checker' ),
        'criteria_description' => '',
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#captions-live',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/captions-live.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#captions-live',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.5',
        'title'    => esc_html__( 'Audio Description (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => '',
        'level'    => 'AA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#audio-description-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/audio-description-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#audio-description-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.6',
        'title'    => esc_html__( 'Sign Language (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => '',
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#sign-language-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/sign-language-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#sign-language-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.7',
        'title'    => esc_html__( 'Extended Audio Description (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => '',
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Blind and low vision people', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#extended-audio-description-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/extended-audio-description-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#extended-audio-description-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.8',
        'title'    => esc_html__( 'Media Alternative (Prerecorded)', 'accessibility-checker' ),
        'criteria_description' => '',
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'Deaf-blind people', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#media-alternative-prerecorded',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/media-alternative-prerecorded.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#media-alternative-prerecorded',
        'tags'     => [],
    ],
    [
        'number'   => '1.2.9',
        'title'    => esc_html__( 'Audio-only (Live)', 'accessibility-checker' ),
        'criteria_description' => '',
        'level'    => 'AAA',
        'version'  => '2.0',
        'guidelines' => esc_html__( '1.2 Time-based Media', 'accessibility-checker' ),
        'principles' => esc_html__( 'Perceivable', 'accessibility-checker' ),
        'impacted_populations' => [
            esc_html__( 'Deaf and hard of hearing people', 'accessibility-checker' ),
            esc_html__( 'Language learners', 'accessibility-checker' ),
        ],
        'how_to_meet_url' => 'https://www.w3.org/WAI/WCAG21/quickref/#audio-only-live',
        'understanding_url' => 'https://www.w3.org/WAI/WCAG21/Understanding/audio-only-live.html',
        'wcag_url' => 'https://www.w3.org/TR/WCAG21/#audio-only-live',
        'tags'     => [],
    ],
    // Continue for all other rows in your CSV...
];