name: Coverage Report

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: xdebug
        github-token: ${{ secrets.PUBLIC_REPO_ACCESS }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

      # Some images won't have svn available. Install it if that's the case.
    - name: Install SVN
      run: |
       if ! command -v svn &> /dev/null; then
         echo "Installing SVN..."
         sudo apt-get update --allow-releaseinfo-change || { echo "Failed to update package lists"; exit 1; }
         sudo apt-get install -y subversion || { echo "Failed to install SVN"; exit 1; }
       else
         echo "SVN is already installed"
       fi

    - name: Install WP
      shell: bash
      run: tests/bin/install-wp-tests.sh wordpress_tests root '' 127.0.0.1:3306 ${{ matrix.wp_version }}

    - name: Run PHPUnit and generate reports in clover and html format
      run: ./vendor/bin/phpunit --coverage-clover=./coverage/clover.xml --coverage-html=./coverage/html

    - name : Attach zipped coverage report as workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: ./coverage/coverage-html.zip

    - name: Convert coverage clover format to Coveralls format
      run: |
        composer global require php-coveralls/php-coveralls
        ~/.composer/vendor/bin/php-coveralls -v -x ./coverage/clover.xml -o ./coverage/coveralls.json
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_RUN_ID: ${{ github.run_id }}

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/coveralls.json
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_RUN_ID: ${{ github.run_id }}
