name: Coverage Report

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: xdebug

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPUnit and generate reports in clover and html format
      run: ./vendor/bin/phpunit --coverage-clover=./coverage/clover.xml --coverage-html=./coverage/html

    - name: Zip html coverage report
      run: |
        zip -r ./coverage/coverage-html.zip ./coverage/html

    - name : Attach zipped coverage report as workflow artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-html
        path: ./coverage/coverage-html.zip

    - name: Convert coverage clover format to Coveralls format
      run: |
        composer global require php-coveralls/php-coveralls
        ~/.composer/vendor/bin/php-coveralls -v -x ./coverage/clover.xml -o ./coverage/coveralls.json

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/coveralls.json
